### ISSUE TITLE
Keywords are unnecessarily escaped

### ISSUE THREAD

**Issue by jnm2** [paul1956/CSharpToVB#15]
Source line: https://github.com/dotnet/roslyn/blob/c0a1d1ec94efc2b4fcc2334580c84741e10e45ef/src/EditorFeatures/CSharpTest/SimplifyInterpolation/SimplifyInterpolationTests.cs#L44

Expected:

```vb
                diagnostics.Select(Function(d) (d.Descriptor.Id, d.Severity)))
```

Actual:

```vb
                diagnostics.[Select](AddressOf Function(d) (d.Descriptor.Id, d.Severity)))
```

**Comment by paul1956** [comment]
Fixed in latest commit. Please provide any other examples.
