### ISSUE TITLE
AddressOf should not be generated for lambdas

### ISSUE THREAD

**Issue by jnm2** [paul1956/CSharpToVB#16]
This results in:

> BC30577 'AddressOf' operand must be the name of a method (without parentheses).

Source line: https://github.com/dotnet/roslyn/blob/c0a1d1ec94efc2b4fcc2334580c84741e10e45ef/src/EditorFeatures/CSharpTest/SimplifyInterpolation/SimplifyInterpolationTests.cs#L44

Expected:

```vb
                diagnostics.Select(Function(d) (d.Descriptor.Id, d.Severity)))
```

Actual:

```vb
                diagnostics.[Select](AddressOf Function(d) (d.Descriptor.Id, d.Severity)))
```

**Comment by paul1956** [comment]
I will work on this, before I didn't add AddressOf and many things broke. I will add this test.

**Comment by paul1956** [comment]
Fixed in latest commit. Please provide any other examples.
