### ISSUE TITLE
Options must be ON

### ISSUE THREAD

**Issue by VBAndCs** [paul1956/CSharpToVB#20]
You add these statements at top of each converted file:
```VB.NET
Option Explicit Off
Option Infer On
Option Strict Off
```

In fact this will hide many conversion errors. C# is a strict language, so the code converted from it must work will VB option Explicit  and Strict  are On:
```VB.NET
Option Explicit On
Option Infer On
Option Strict On
```

For example, tour decision hides this problem:
C#
```C#
if (quantities.TryGetValue(item.Id.ToString(), out var quantity))
```

VB:
```VB.NET
    Dim quantity As Object= Nothing
    If quantities.TryGetValue(item.Id.ToString(), quantity) Then
```

Which will be obvious when truning options off. The correct code is:
```
   Dim quantity As Integer = 0
   If quantities.TryGetValue(item.Id.ToString(), quantity) Then
```

**Comment by VBAndCs** [comment]
It also reviled the source of a runtime exception that took me hours in vain, which discovered a bug in VB as I explained in: https://github.com/dotnet/vblang/issues/507

**Comment by paul1956** [comment]
@VBAndCs Not sure what to do about this one without a more complete example. In general the code tries to figure out the type for var but if it can't which happens a lot in single file conversions it has to default to object. If you add some more of the file I will see what can be done. Once I can easily edit WinForms I plan on adding the ability for the user to specify the 4 Options and the ability to not include them on every file but that does not address this issue, I separated bug #24 on that,

**Comment by paul1956** [comment]
@VBAndCs  Your examples have been converted successfully using folder convert in today's build version 4.1.0.3.
