### ISSUE TITLE
private_set propertes is converted to public properties

### ISSUE THREAD

**Issue by VBAndCs** [paul1956/CSharpToVB#21]
This C# code
```C#
public string BuyerId { get; private set; }
```

is converted to:

```VB.NET
Public Property BuyerId As String
```

but it should be:
```VB.NET
Dim _buyerId As String
Public Property BuyerId As String
   Get
       Return _buyerId
   End Get

   Private Set(value As String)
       _buyerId = value
   End Set
End Property
```

**Comment by paul1956** [comment]
@VBAndCs  I will post a fix for this case tonight. I don't know if it will fix all cases and some comments may be removed (needs more tests) also more comments were picked up around Properties. For MustOverride (Abstract) I don't think VB allows different modifiers for Get and Set. If it is allowed please proved syntax, right now I continue to convert as before.
