### ISSUE TITLE
<RepositoryType> vbproj property isn't standard or might be invalid

### ISSUE THREAD

**Issue by jnm2** [paul1956/CSharpToVB#3]
The reason for the \<RepositoryType> property is to specify the .nuspec `<repository type=` attribute value. I've never seen the value `GitHub` before; with GitHub projects, everyone uses `git` that I've seen. The \<RepositoryType> value is referring to the protocol used to programmatically connect to the `<repository url=` URL.

https://docs.microsoft.com/en-us/nuget/reference/nuspec#repository shows an example which has a GitHub URL and a `git` repository type, so I'm pretty sure that's what it should be:

```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        ...
        <repository type="git" url="https://github.com/NuGet/NuGet.Client.git" branch="dev" commit="e1c65e4524cd70ee6e22abe33e6cb6ec73938cb3" />
        ...
    </metadata>
</package>
```

**Comment by paul1956** [comment]
Fixed in Master
