### ISSUE TITLE
Evaluate type param

### ISSUE THREAD

**Issue by VBAndCs** [paul1956/CSharpToVB#42]
C#:
```
var activateInfo = propertiesToActivate[i];
```

VB:
```VB.NET
Dim activateInfo As PropertyActivator(Of TContext) = propertiesToActivate(i)
```

No need to explicit declaration here. This is OK:
` Dim activateInfo = propertiesToActivate(i)`

But if you have to mention the type, you should evaluate the type param, instead using `TContext` which is the raw generic declaration not a real type. In this context, TContext is evaluated to be `ViewContext()`. You need to use a valid sample to reproduce this case.

**Comment by VBAndCs** [comment]
Similar issue here:
C#:
```C#
                foreach (var item in ViewLocationExpanderValues)
                {
                    hashCodeCombiner.Add(item.Key, StringComparer.Ordinal);
                    hashCodeCombiner.Add(item.Value, StringComparer.Ordinal);
                }
```

VB:
```VB.NET
                For Each item As IEnumerable(Of KeyValuePair(Of String, String)) In ViewLocationExpanderValues
                    _hashCodeCombiner.Add(item.Key, StringComparer.Ordinal)
                    _hashCodeCombiner.Add(item.Value, StringComparer.Ordinal)
                Next
```

The item is of type `KeyValuePair(Of String, String)` not `IEnumerable(Of KeyValuePair(Of String, String))`, and you can avoid this but maintain inference:
```VB.NET
                For Each item In ViewLocationExpanderValues
                    _hashCodeCombiner.Add(item.Key, StringComparer.Ordinal)
                    _hashCodeCombiner.Add(item.Value, StringComparer.Ordinal)
                Next
```

**Comment by paul1956** [comment]
I am getting your desired results when I just convert the snippet. I need a more complete example to debug the issue. I try to avoid type inference when I know the type. The defaults for all my projects are Infer Off, Strict On, Explicit On.

**Comment by VBAndCs** [comment]
You should stick with the original c# code. Inference makes the code shorter and cleaner so more readable. Besides, you write the full qualified names srating with system. Save your self the truple and keep inferencxe. C# and vb are idintical in this aspect.

**Comment by paul1956** [comment]
I now support user setting of Option Infer, I may look at using this for source generation in the future. But it is not high priority.

**Comment by paul1956** [comment]
I now allow the user to specify the options included in the converted code so you can set whatever you want and the converter will include your selections. @VBAndCs if you still have an issue open a new report with enough source to reproduce.
