### ISSUE TITLE
Enclose New with []

### ISSUE THREAD

**Issue by VBAndCs** [paul1956/CSharpToVB#43]
C#:
```C#
var x = Expression.New(constructor, parameter1, parameter2);
```

VB:
```VB.NET
Private x = Expression.New(constructor, parameter1, parameter2)
```

Vb realizes the .New as a call to the constructor. Use .[New] as C# means to call a method named `New`. This differs than using base in C# that translates to a call to the `MyBase.New` . The result should be:
VB:
```VB.NET
Private x = Expression.[New](constructor, parameter1, parameter2)
```

**Comment by paul1956** [comment]
Fixed in 4.2.11.0
