### ISSUE TITLE
dynamic

### ISSUE THREAD

**Issue by VBAndCs** [paul1956/CSharpToVB#46]
C#
`public dynamic ViewBag => ViewContext?.ViewBag;`

VB:
```
Public ReadOnly Property ViewBag As dynamic
    Get
        Return ViewContext?.ViewBag
    End Get
End Property
```

Change dynamic to Object in VB.

**Comment by paul1956** [comment]
Will be fixed in 4.2.11.0, Converter 3.3.0.0
