### ISSUE TITLE
Error in LineNumbersForRichTextBox

### ISSUE THREAD

**Issue by elGuille-info** [paul1956/CSharpToVB#54]
When checking 
```vb
If String.IsNullOrWhiteSpace(Me.ZParent.Text) Then
```
A null error is thrown because Me.ZParent is Nothing.

I check if it's nothing then return.

``` vb
' Da error en la siguiente comprobación de que esto es nulo (It gives error in the following check that this is null)
If Me.ZParent Is Nothing Then
    Exit Sub
End If

If String.IsNullOrWhiteSpace(Me.ZParent.Text) Then
    Exit Sub
End If
```

Guillermo

**Comment by elGuille-info** [comment]
It happened when no showing line numbers (I don't know why) but later I try (with your last update) and works (the lines are shown)

Guillermo

**Comment by paul1956** [comment]
The only time Me.ZParent is nothing is if Form1 is opened in designer and corrupts the designer file. Otherwise it is set in the lines below in Form1.Designer.VB.
```
        Me.LineNumbersForConversionInput.ParentRichTextBox = Me.ConversionInput
        Me.LineNumbersForConversionOutput.ParentRichTextBox = Me.ConversionOutput

```
If you try to run LineNumbersForRichTextBox without setting Parent the control will fail.

**Comment by paul1956** [comment]
I am going to close assuming the designer file was corrupted. This is a VS issue.

**Comment by paul1956** [comment]
@elGuille-info If you ever open Form1 in Designer it corrupts the file and deletes key parts and lots of things don't work. There is noting I can do about it except tell people not to open the Form1 in designer. If you are using git and open the form and then do Git Compare with Unmodified you will see all the unexpected changes you and then do a Git undo on 3 files to repair.

**Comment by elGuille-info** [comment]
yes that happened to me on .net preview but no when RC goes out... in that time I had to do copies each time I want to change something. I am newie to GitHub and related :-)I'll have more care and follow your tip.Thanks!Guillermo

**Comment by paul1956** [comment]
I am fine helping with GitHub not that I am expert.
