### ISSUE TITLE
Add editing keys to both panels, now you must use the context menu for edit actions

### ISSUE THREAD

**Issue by elGuille-info** [paul1956/CSharpToVB#55]
If I want to select code o paste or copy I must use the contexte menu, but it's easiest if I coudl use the short-cut keys:
For example Ctrl+A for select all the text.
It's shown in the context menu but isn't works.

Thank you.
Guillermo

**Comment by paul1956** [comment]
@elGuille-info that used to work I need to find out when it broke. I will look this week.

**Comment by paul1956** [comment]
@elGuille-info  Fixed in 5.0.0.18/5.0.0.8

**Comment by paul1956** [comment]
@elGuille-info  Fixed in 5.0.0.18/5.0.0.8
