### ISSUE TITLE
CI build to validate PRs

### ISSUE THREAD

**Issue by jnm2** [paul1956/CSharpToVB#6]
Would you be interested in adding a GitHub Actions CI build that simply builds the solution and runs all tests? That way the build errors I missed in https://github.com/paul1956/CSharpToVB/pull/2 would have prevented the PR from being merged without overriding.

**Comment by paul1956** [comment]
Yes, but the real tests are the 42 that use Roslyn Source.

**Comment by jnm2** [comment]
I set up a CI build first without the Roslyn tests, then with them. The Roslyn tests are currently failing, so we cannot use them to validate PRs until that is fixed. Not only do they fail, but they take a super long time to run. 14 minutes and still running! https://github.com/jnm2/CSharpToVB/runs/507932037

The weird thing about it is that the Roslyn codebase is a moving target, so if they do something you haven't seen before, your master branch will be considered broken and all builds will fail even for PRs that are not related.

**Comment by paul1956** [comment]
Yes, I check new versions of Roslyn maybe monthly and they take over an hour based so yes it is better to not include them.

**Comment by paul1956** [comment]
Fixed by @jnm2
