### ISSUE TITLE
Copyright shown in application does not match the copyright in the source repository

### ISSUE THREAD

**Issue by jnm2** [paul1956/CSharpToVB#7]
The source code that produces the app:

https://github.com/paul1956/CSharpToVB/blob/f39271e886d90f9517527fbe7fb2e7a60ba1a20f/License.txt#L3

The metadata on the build artifacts and the message displayed in the app:

https://github.com/paul1956/CSharpToVB/blob/f39271e886d90f9517527fbe7fb2e7a60ba1a20f/CSharpToVB/CSharpToVB.vbproj#L28

**Comment by paul1956** [comment]
Fixed, thanks
