### ISSUE TITLE
Project file not converted when convert solution

### ISSUE THREAD

**Issue by Whismeril** [paul1956/CSharpToVB#70]
Hi
Converting a solution with 2 project, this message appears twice
![image](https://user-images.githubusercontent.com/49691966/108098073-38beff00-7083-11eb-9f37-85b8514e4876.png)

At the end this message appears
![image](https://user-images.githubusercontent.com/49691966/108098415-9fdcb380-7083-11eb-9a8e-b77891f661d9.png)

But no file *.csproj is converted to *.vbproj

Testing with lasted version, on branch "Support 16.8".
It was the same with previous version.

Here project I've converted
[project.zip](https://github.com/paul1956/CSharpToVB/files/5990399/project.zip)

**Comment by paul1956** [comment]
Two different messages, first is about the project file. I can only convert SDK style project files. The second is about the files in the project. If you have a better way to say it let me know. Maybe the second should say the "The C# files in 2 project were converted successfully" Let me know if you have other ideas.

**Comment by paul1956** [comment]
I did fix the message so they don't say SourceFIleName but instead actually show the name. I think with that and the other text changes I can close this. Feel free to reopen if you still see an issue.

**Comment by Whismeril** [comment]
The last message may be "All files except ....  have been converted successfully"

**Comment by paul1956** [comment]
@Whismeril if you have any errors they are reported individually and you will have to option of continuing or stopping.
