### ISSUE TITLE
DarkMode - Slight tweaks

### ISSUE THREAD

**Issue by DualBrain** [paul1956/CSharpToVB#73]
I'm still trying to wrap my head around how to manage my fork compared to your changes; so have been experimenting locally with your repo instead of a fork.  So the following changes were made in an effort to slightly improve the look of things as well as better handle certain cases where forcing Padding might not be a good idea.

# ThemeSupport.vb

- Remove setting the Padding; let this take place in via the WinForms designer.
- Remove setting the BorderStyle; again, let designer be the authority.

# Form1.Designer.vb

## ConversionInputPanelEx

- Set BorderStyle = FixedSingle

## ConversionInput

- Set BorderStyle = None
- Set Dock = Fill

## ConversionOutputPanelEx

- Set BorderStyle = FixedSingle

## ConversionOutput

- Set BorderStyle = None
- Set Dock = Fill

## FileListPanelEx

- Set BorderStyle = FixedSingle

## FileListListBox

- Set BorderStyle = None
- Set DockStyle = Fill

## ErrorListPanelEx

- Set BorderStyle = FixedSingle

## ErrorListListBox

- Set BorderStyle = None
- Set DockStyle = Fill
- Remove Anchor

Making these changes does seem to improve the look a bit.  I'm currently exploring how to handle scrollbars... so will do a separate update regarding that (once I have it figured out).

**Comment by paul1956** [comment]
Fixed
